title: Invest in Open Infrastructure
description: An effort to enable durable, scalable, and long lasting open scientific and scholarly infrastructure to emerge, thrive, and deliver its benefits on a global scale.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
